# Generated by Django 4.1.1 on 2022-09-23 20:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MidCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='TopCategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='midcategory',
            name='top_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.topcategory'),
        ),
        migrations.AddField(
            model_name='botcategory',
            name='mid_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.midcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='bot_category',
            field=models.ManyToManyField(to='products.botcategory'),
        ),
    ]
