# Generated by Django 4.1.1 on 2022-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_botcategory_midcategory_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products'),
        ),
    ]
