# Generated by Django 4.1.1 on 2022-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_size_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midcategory',
            name='category_image',
            field=models.ImageField(blank=True, default='categories/default.jpg', null=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='category_image',
            field=models.ImageField(blank=True, default='categories/default.jpg', null=True, upload_to='categories'),
        ),
    ]
