# Generated by Django 4.1.1 on 2022-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_old_price_product_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcategory',
            name='category_image',
            field=models.ImageField(blank=True, default='categories/default.jpg', null=True, upload_to='categories'),
        ),
    ]
